### ISSUE TITLE
5. Code structuring and refactoring

### ISSUE THREAD

**Issue by jorgechb** [jorgechb/MLOps_Team14#8]
Structure Machine Learning models in an organized way and apply object-oriented programming principles.

- Organize the code into well-defined modules and functions.
- Apply object-oriented programming principles to improve code structure.
- Refactor existing code to enhance its efficiency and maintainability.

**Comment by dvillan** [comment]
- [x] Create configuration file 
- [ ] Refactor prototype into reusable modules
